apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    creator: iter8
  name: iter8-analytics
  namespace: iter8-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    creator: iter8
  name: iter8-controller
  namespace: iter8-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    creator: iter8
  name: iter8-handlers
  namespace: iter8-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    creator: iter8
  name: iter8-istio-dr
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    creator: iter8
  name: iter8-istio-vs
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    creator: iter8
  name: iter8-ksvc-reader-writer
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    creator: iter8
  name: iter8-vs-reader-writer
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    creator: iter8
  name: iter8-istio-dr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iter8-istio-dr
subjects:
- kind: ServiceAccount
  name: iter8-controller
  namespace: iter8-system
- kind: ServiceAccount
  name: iter8-handlers
  namespace: iter8-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    creator: iter8
  name: iter8-istio-vs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iter8-istio-vs
subjects:
- kind: ServiceAccount
  name: iter8-controller
  namespace: iter8-system
- kind: ServiceAccount
  name: iter8-handlers
  namespace: iter8-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    creator: iter8
  name: iter8-ksvc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iter8-ksvc-reader-writer
subjects:
- kind: ServiceAccount
  name: iter8-controller
  namespace: iter8-system
- kind: ServiceAccount
  name: iter8-handlers
  namespace: iter8-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    creator: iter8
  name: iter8-vs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iter8-vs-reader-writer
subjects:
- kind: ServiceAccount
  name: iter8-controller
  namespace: iter8-system
- kind: ServiceAccount
  name: iter8-handlers
  namespace: iter8-system
